### ISSUE TITLE
Macro for setting particular span

### ISSUE THREAD

**Issue by TedDriggs** [dtolnay/respan#1]
Can we add a third macro that allows directly passing the span we want to use, similar to the private `respan` function already present?

**Comment by dtolnay** [comment]
I would prefer not to build that into this crate.

**Comment by TedDriggs** [comment]
Is that because you'd like to keep this crate's scope small, or because there's some reason that functionality is harmful/too easily misused?

I ask because I could offer it as part of [`darling::util`](https://docs.rs/darling/latest/darling/util/index.html), but if there's some nuance that makes it dangerous that I'm not seeing, I'd prefer not to give my crate's customers a new footgun.

**Comment by TedDriggs** [comment]
After looking at this more closely, I think I see why this request doesn't align with the spirit of the crate. I also think this crate does the opposite of what I had understood.

On initial reading, I'd thought the `respan` function was similar to the one from dtolnay/syn#309, that is now also being used [here](https://github.com/colin-kiegel/rust-derive-builder/blob/master/derive_builder_core/src/change_span.rs) in derive_builder to avoid confusing issues with spans and custom "crate roots".

The piece I missed was:

```rust
token.set_span(original_span.resolved_at(site));
```

So I thought this crate would change the spans for diagnostics, while in reality it changes the spans for hygiene.

I'm going to move forward with adding a function to `darling::util` for changing the span of a `TokenStream` for diagnostic purposes, and I will avoid calling it `respan` to minimize the risk that users confuse that function's intent and this crate's intent.
